Вроде как сделал
maxpurrp/phone_book pull request #3
Opened 2022-12-20 22:12 UTC by maxpurrp

ready

2022-12-20 22:23 UTC, paulpaul9740 requested changes

2022-12-20 22:23 UTC, paulpaul9740 commented on cataloque.py
> +    print("save  Сохранить текущую версию справочника")
актуализировать эту функцию

2022-12-20 22:23 UTC, paulpaul9740 commented on cataloque.py
> +def add_file():
лучше load_from_file или load - файл то мы никуда не добавляем, а вот его содержимое загружаем

2022-12-20 22:23 UTC, paulpaul9740 commented on cataloque.py
> +    x=input()
используем осознанные названия(path, filepath , path_to_file...)

2022-12-20 22:23 UTC, paulpaul9740 commented on cataloque.py
> +    for line in f:
можно сразу ```for line.strip() in f```

2022-12-20 22:23 UTC, paulpaul9740 commented on cataloque.py
> +        x=line.split(":")
используем осознанные названия(item,record...)

2022-12-20 22:23 UTC, paulpaul9740 commented on cataloque.py
> +    print("Введите путь для загрузки файла")
почему ввод находится тут? необходимо соблюдать уже выбранный подход - считывать аргументы вне функции, валидировать их количество, передавать в функцию

2022-12-20 22:23 UTC, paulpaul9740 commented on cataloque.py
> +        print("Введите путь для сохранения файла")
тж самое, что и с load - вынести ввод

2022-12-20 23:34 UTC, paulpaul9740 requested changes

2022-12-20 23:34 UTC, paulpaul9740 commented on cataloque.py
> +            print("<add> or <new>")
убрать <> - это конкретные слова, которые пользоваетль собирается вводить. а угловые скобки говорят о том, что тут нужно "что-то подставить"

2022-12-20 23:34 UTC, paulpaul9740 commented on cataloque.py
> +        path_1=input()
1) вынести общий код
2) почему инпут оказался опять внутри функции save?
А так же: предположим, что код выносить тут не нужно. в таких ситуациях, когда у тебя есть 2 переменные в блоках if else, не нужно называть их _1  и _2, тут логичнее использовать одну переменную, так как код при разных условиях не пересечется

2022-12-20 23:36 UTC, paulpaul9740 commented on cataloque.py
> +    print("save  Сохранить текущую версию справочника")
все еще актуализировать эту функцию

2022-12-26 13:17 UTC, paulpaul9740 commented on cataloque.py
> +            choise=input()
предлагаю все же сохранить единообразность интерфейса - то есть `save <file> [add|new]` - чтоб это вводилось сразу, без вопросов пользователю. заметь, add и new  - в квадратных скобках: предлагаю сделать этот аргумент необязательным, и если пользователь не указал его, то выбирать "add"(значение по умолчанию тип)
для load аналогично - `load <file>`

2022-12-26 13:19 UTC, maxpurrp commented on cataloque.py
> +            choise=input()
понял

2022-12-26 23:08 UTC, paulpaul9740 commented on cataloque.py
> +                print("Введите путь для загрузки файла")
в load все аргументы пока обязательны, поэтому в случае `len == 1`(и не только 1) должна печататься ошибка

2022-12-26 23:09 UTC, paulpaul9740 commented on cataloque.py
> +                save(choise,path)
`save(choise,path)` - общий код для двух веток

2022-12-26 23:09 UTC, paulpaul9740 commented on cataloque.py
> +            if len(command)==3:
обработать ошибки в случае ввода другого количества аргументов

2022-12-29 21:36 UTC, merged